spring:
  application:
    name: producer-service
  kafka:
    # Use localhost:9092 when running from your IDE/terminal. 
    # Use kafka:29092 if running this app inside the Docker compose network.
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
server:
  port: 8080
