// AUTO-GENERATED by scripts/auto-discover-content.mjs
// Do not edit manually. Generated automatically on predev / prebuild.
import type { ComponentType } from 'react';

import RaftVisualizer from './raft-consensus/RaftVisualizer';
import ConsistentHashingVisualizer from './consistent-hashing/ConsistentHashingVisualizer';
import BloomFilterVisualizer from './bloom-filter/BloomFilterVisualizer';
import RabbitMQVisualizer from './rabbitmq/RabbitMQVisualizer';
import KafkaVisualizer from './apache-kafka/KafkaVisualizer';
import RateLimiterVisualizer from './api-rate-limiter/RateLimiterVisualizer';

export const visualizerRegistry: Record<string, ComponentType<any>> = {
  'raft-consensus': RaftVisualizer,
  'consistent-hashing': ConsistentHashingVisualizer,
  'bloom-filter': BloomFilterVisualizer,
  'rabbitmq': RabbitMQVisualizer,
  'apache-kafka': KafkaVisualizer,
  'api-rate-limiter': RateLimiterVisualizer,
};

export function hasVisualizer(slug: string): boolean {
  return Boolean(visualizerRegistry[slug]);
}

export const registeredLabSlugs = Object.keys(visualizerRegistry);
